local harpoon = require("harpoon")

local function mapbuffer(key, func, desc)
  vim.keymap.set("n", key, func, { noremap = true, silent = true, desc = desc, buffer = true })
end

mapbuffer("1", function()
  harpoon:list():select(1)
end)
mapbuffer("2", function()
  harpoon:list():select(2)
end)
mapbuffer("3", function()
  harpoon:list():select(3)
end)
mapbuffer("4", function()
  harpoon:list():select(4)
end)
mapbuffer("5", function()
  harpoon:list():select(5)
end)

mapbuffer("m", function()
  harpoon.ui:select_menu_item()
end, "Map 'm' to Enter")
